// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlatpickrController from "./flatpickr_controller.js"
application.register("flatpickr", FlatpickrController)

import FormDisplayController from "./form_display_controller.js"
application.register("form-display", FormDisplayController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import InsertInListController from "./insert_in_list_controller.js"
application.register("insert-in-list", InsertInListController)

import MapController from "./map_controller.js"
application.register("map", MapController)
